/** Shared types for GitLaw Pro. Unknown matter privacy defaults to real mandate in privacy helpers. */
export interface KanzleiSettings {
  name: string
  address: string
  contact: string
  logoDataUrl?: string
  anwaltName: string
  kammerId?: string
  firstName?: string
}

export interface MatterPrivacyState {
  dataMode: 'synthetic' | 'real_mandate'
  externalAiConsentOnFile?: boolean
  /** Opaque evidence reference only; never the consent document contents. */
  externalAiConsentEvidenceRef?: string
  externalServiceNecessaryAttested?: boolean
  externalAiPurpose?: string
  pseudonymousCaseRef?: string
  reviewedAt?: string
  reviewedBy?: string
}

export interface MandantCase {
  id: string
  mandantName: string
  aktenzeichen: string
  description: string
  createdAt: string
  updatedAt: string
  researchIds: string[]
  letterIds: string[]
  status: 'aktiv' | 'archiviert'
  fristDatum?: string
  fristBezeichnung?: string
  mandantEmail?: string
  tasks?: TeamTask[]
  documents?: CaseDocument[]
  documentJobs?: DocumentJob[]
  relevantParagraphs?: RelevantParagraph[]
  mandatsartId?: string
  checklistStates?: Record<string, 'received' | 'pending' | 'problem'>
  caseStatus?: string
  statusHistory?: StatusHistoryEntry[]
  behoerde?: string
  behoerdePLZ?: string
  privacy?: MatterPrivacyState
}

export interface StatusHistoryEntry {
  status: string
  changedAt: string
  changedBy: string
}

export interface TeamTask {
  id: string
  title: string
  done: boolean
  assignee?: string
  createdAt: string
  completedAt?: string
}

export type CaseTaskType =
  | 'unterlagen_pruefen'
  | 'mandant_erinnern'
  | 'antrag_vorbereiten'
  | 'behoerde_nachfassen'
  | 'nachforderung_pruefen'
  | 'frist_kontrollieren'
  | 'anwaltliche_pruefung'
  | 'sonstiges'

export type CaseTaskStatus = 'open' | 'done' | 'cancelled'

export interface CaseTask {
  id: string
  caseId: string
  title: string
  type: CaseTaskType
  dueDate?: string
  status: CaseTaskStatus
  createdAt: string
  completedAt?: string
  autoGenerated: boolean
}

export interface CaseDocument {
  id: string
  originalName: string
  internalName: string
  mimeType: string
  sizeBytes: number
  uploadedAt: string
  uploadedBy?: string
  category?: IntakeAttachmentMeta['category']
  languageHint?: IntakeAttachmentMeta['languageHint']
  dataUrl?: string
  storageMode?: 'local_inline' | 'server_vault'
  serverDocumentId?: string
  storageProvider?: string
  checksumSha256?: string
  textContent?: string
  ocrText?: string
  translatedTextDe?: string
  translationReviewed?: boolean
  checklistItemId?: string
  photoSlotId?: string
  kind?: 'vollmacht' | 'standard' | 'anwalt_upload'
  reviewStatus?: 'pending' | 'approved' | 'rejected'
  reviewedBy?: string
  reviewedAt?: string
  reviewComment?: string
  deletedAt?: string
}

export interface ResearchQuery {
  id: string
  caseId?: string
  question: string
  answer: string
  citations: Citation[]
  createdAt: string
  reviewed: boolean
  approvedAnswer?: string
}

export type VerificationReason =
  | 'law_not_found'
  | 'paragraph_not_found'
  | 'repealed'
  | 'could_not_parse'

export interface Citation {
  display: string
  lawId: string
  section: string
  verified: boolean
  excerpt?: string
  verificationReason?: VerificationReason
  verificationHint?: string
}

export interface GeneratedLetter {
  id: string
  caseId?: string
  templateId: string
  templateTitle: string
  fields: Record<string, string>
  body: string
  createdAt: string
}

export interface AuditEntry {
  id: string
  at: string
  actor: string
  action:
    | 'login'
    | 'case.create'
    | 'case.archive'
    | 'case.task.add'
    | 'case.task.done'
    | 'case.document.upload'
    | 'doc.ocr.queue'
    | 'doc.translate.queue'
    | 'doc.review.done'
    | 'research.query'
    | 'letter.generate'
    | 'pdf.export'
    | 'settings.update'
    | 'intake.received'
    | 'reminder.generate'
    | 'reminder.sent'
    | 'advoware.import'
  detail: string
  caseId?: string
  tenantId?: string
  actorRole?: 'owner' | 'anwalt' | 'paralegal' | 'assistenz' | 'assistant' | 'read_only'
  prevHash?: string
  hash?: string
}

export interface CustomTemplate {
  id: string
  title: string
  description?: string
  body: string
  placeholders: string[]
  createdAt: string
  updatedAt: string
}

export interface ParagraphNote {
  key: string
  lawId: string
  section: string
  body: string
  updatedAt: string
}

export interface IntakeEntry {
  id: string
  caseId?: string
  targetSlug?: string
  submittedAt: string
  name: string
  email?: string
  phone?: string
  anliegen: string
  gewuenschterAusgang?: string
  dringlichkeit?: 'niedrig' | 'mittel' | 'hoch' | 'akut'
  fristBekannt?: boolean
  attachments?: IntakeAttachmentMeta[]
  source?: 'form' | 'email'
  senderEmail?: string
  reviewed: boolean
}

export interface IntakeAttachmentMeta {
  originalName: string
  internalName: string
  mimeType: string
  sizeBytes: number
  category?: 'foto' | 'bescheid' | 'vertrag' | 'chat' | 'sonstiges'
  languageHint?: 'de' | 'vi' | 'en' | 'tr' | 'ar' | 'other'
}

export interface DocumentJob {
  id: string
  documentId?: string
  attachmentInternalName: string
  type: 'ocr' | 'translate'
  status: 'queued' | 'processing' | 'done'
  requestedAt: string
  requestedBy?: string
  sourceLanguage?: IntakeAttachmentMeta['languageHint']
  targetLanguage?: 'de'
  note?: string
}

export interface ApprovedAnswerMemory {
  id: string
  tenantId?: string
  caseId?: string
  question: string
  approvedAnswer: string
  practiceHint?: string
  createdAt: string
  sourceResearchId?: string
}

export interface ParagraphLookup {
  found: boolean
  lawId: string
  section: string
  text?: string
}

export interface RelevantParagraph {
  lawId: string
  section: string
  display: string
  source: string
  addedAt: string
}

export interface RechtsprechungsAlert {
  id: string
  caseId?: string
  paragraph: { lawId: string; section: string; display: string }
  court: string
  rulingDate: string
  title: string
  summary: string
  url?: string
  createdAt: string
}

export type MandatsartCategory =
  | 'migration'
  | 'strafrecht'
  | 'familie'
  | 'sozial'
  | 'sonstiges'

export type DocumentRequirementLevel = 'required' | 'optional' | 'conditional'

export interface PhotoSlot {
  id: string
  label: string
  labelVi?: string
}

export interface ChecklistItem {
  id: string
  label: string
  labelVi?: string
  description?: string
  level: DocumentRequirementLevel
  conditionalNote?: string
  acceptedFormats?: string[]
  typicalIssues?: string[]
  category?:
    | 'identitaet'
    | 'aufenthalt'
    | 'familie'
    | 'wohnen'
    | 'einkommen'
    | 'gesundheit'
    | 'sprache'
    | 'biometrie'
    | 'sonstiges'
  requiredPhotoCount?: number
  photoSlots?: PhotoSlot[]
}

export interface MandatsartChecklist {
  id: string
  title: string
  titleVi?: string
  category: MandatsartCategory
  description: string
  legalBasis?: string[]
  typicalDuration?: string
  requiredDocuments: ChecklistItem[]
}
