/**
 * Shared types for GitLaw Pro (Anwält:innen-Tier).
 *
 * Privacy rule: a matter without an explicit classification is treated as
 * REAL MANDATE data by the lawyer-safe helpers. Demo seed data must opt in
 * to `privacy.dataMode = 'synthetic'` explicitly; there is no implicit
 * "probably demo" downgrade for unknown cases.
 */

export interface KanzleiSettings {
  name: string
  address: string
  contact: string
  logoDataUrl?: string
  anwaltName: string
  kammerId?: string
  firstName?: string
}

export interface MatterPrivacyState {
  /** Defaults to real_mandate when absent. */
  dataMode: 'synthetic' | 'real_mandate'
  /** Evidence marker only — never store the signed consent document in this field. */
  externalAiConsentOnFile?: boolean
  /** Opaque reference/hash/path to evidence kept in the Kanzlei record. */
  externalAiConsentEvidenceRef?: string
  /** Lawyer attestation that external AI is necessary for this workflow. */
  externalServiceNecessaryAttested?: boolean
  /** Narrow purpose shown in the privacy receipt. */
  externalAiPurpose?: string
  /** Non-identifying reference sent to the privacy gateway. */
  pseudonymousCaseRef?: string
  /** ISO timestamp of the last lawyer privacy review for this matter. */
  reviewedAt?: string
  /** User/lawyer identifier, not client PII. */
  reviewedBy?: string
}

export interface MandantCase {
  id: string
  mandantName: string
  aktenzeichen: string
  description: string
  createdAt: string
  updatedAt: string
  researchIds: string[]
  letterIds: string[]
  status: 'aktiv' | 'archiviert'
  fristDatum?: string
  fristBezeichnung?: string
  mandantEmail?: string
  tasks?: TeamTask[]
  documents?: CaseDocument[]
  documentJobs?: DocumentJob[]
  relevantParagraphs?: RelevantParagraph[]
  mandatsartId?: string
  checklistStates?: Record<string, 'received' | 'pending' | 'problem'>
  caseStatus?: string
  statusHistory?: StatusHistoryEntry[]
  behoerde?: string
  behoerdePLZ?: string
  /** Privileged-data classification and evidence gates for this matter. */
  privacy?: MatterPrivacyState
}

export interface StatusHistoryEntry {
  status: string
  changedAt: string
  changedBy: string
}

export interface TeamTask {
  id: string
  title: string
  done: boolean
  assignee?: string
  createdAt: string
  completedAt?: string
}

export type CaseTaskType =
  | 'unterlagen_pruefen'
  | 'mandant_erinnern'
  | 'antrag_vorbereiten'
  | 'behoerde_nachfassen'
  | 'nachforderung_pruefen'
  | 'frist_kontrollieren'
  | 'anwaltliche_pruefung'
  | 'sonstiges'

export type CaseTaskStatus = 'open' | 'done' | 'cancelled'

export interface CaseTask {
  id: string
  caseId: string
  title: string
  type: CaseTaskType
  dueDate?: string
  status: CaseTaskStatus
  createdAt: string
  completedAt?: string
  autoGenerated: boolean
}

export interface CaseDocument {
  id: string
  originalName: string
  internalName: string
  mimeType: string
  sizeBytes: number
  uploadedAt: string
  uploadedBy?: string
  category?: IntakeAttachmentMeta['category']
  languageHint?: IntakeAttachmentMeta['languageHint']
  dataUrl?: string
  storageMode?: 'local_inline' | 'server_vault'
  serverDocumentId?: string
  storageProvider?: string
  checksumSha256?: string
  textContent?: string
  ocrText?: string
  translatedTextDe?: string
  translationReviewed?: boolean
  checklistItemId?: string
  photoSlotId?: string
  kind?: 'vollmacht' | 'standard' | 'anwalt_upload'
  reviewStatus?: 'pending' | 'approved' | 'rejected'
  reviewedBy?: string
  reviewedAt?: string
  reviewComment?: string
  deletedAt?: string
}

export interface ResearchQuery {
  id: string
  caseId?: string
  question: string
  answer: string
  citations: Citation[]
  createdAt: string
  reviewed: boolean
  approvedAnswer?: string
}

export type VerificationReason =
  | 'law_not_found'
  | 'paragraph_not_found'
  | 'repealed'
  | 'could_not_parse'

export interface Citation {
  display: string
  lawId: string
  section: string
  verified: boolean
  excerpt?: string
  verificationReason?: VerificationReason
  verificationHint?: string
}

export interface GeneratedLetter {
  id: string
  caseId?: string
  templateId: string
  templateTitle: string
  fields: Record<string, string>
  body: string
  createdAt: string
}

export interface AuditEntry {
  id: string
  at: string
  actor: string
  action:
    | 'login'
    | 'case.create'
    | 'case.archive'
    | 'case.task.add'
    | 'case.task.done'
    | 'case.document.upload'
    | 'doc.ocr.queue'
    | 'doc.translate.queue'
    | 'doc.review.done'
    | 'research.query'
    | 'letter.generate'
    | 'pdf.export'
    | 'settings.update'
    | 'intake.received'
    | 'reminder.generate'
    | 'reminder.sent'
    | 'advoware.import'
  detail: string
  caseId?: string
  tenantId?: string
  actorRole?: 'owner' | 'anwalt' | 'paralegal' | 'assistenz' | 'assistant' | 'read_only'
  prevHash?: string
  hash?: string
}

export interface CustomTemplate {
  id: string
  title: string
  description?: string
  body: string
  placeholders: string[]
  createdAt: string
  updatedAt: string
}

export interface ParagraphNote {
  key: string
  lawId: string
  section: string
  body: string
  updatedAt: string
}

export interface IntakeEntry {
  id: string
  caseId?: string
  targetSlug?: string
  submittedAt: string
  name: string
  email?: string
  phone?: string
  anliegen: string
  gewuenschterAusgang?: string
  dringlichkeit?: 'niedrig' | 'mittel' | 'hoch' | 'akut'
  fristBekannt?: boolean
  attachments?: IntakeAttachmentMeta[]
  source?: 'form' | 'email'
  senderEmail?: string
  reviewed: boolean
}

export interface IntakeAttachmentMeta {
  originalName: string
  internalName: string
  mimeType: string
  sizeBytes: number
  category?: 'foto' | 'bescheid' | 'vertrag' | 'chat' | 'sonstiges'
  languageHint?: 'de' | 'vi' | 'en' | 'tr' | 'ar' | 'other'
}

export interface DocumentJob {
  id: string
  documentId?: string
  attachmentInternalName: string
  type: 'ocr' | 'translate'
  status: 'queued' | 'processing' | 'done'
  requestedAt: string
  requestedBy?: string
  sourceLanguage?: IntakeAttachmentMeta['languageHint']
  targetLanguage?: 'de'
  note?: string
}

/** Fields below are unchanged domain helpers used by existing Pro modules. */
export interface RelevantParagraph {
  lawId: string
  section: string
  display: string
  source?: string
  addedAt?: string
}

export interface RechtsprechungsAlert {
  id: string
  lawId: string
  section: string
  title: string
  summary: string
  sourceUrl?: string
  createdAt: string
  read?: boolean
}

export interface ApprovedAnswerMemory {
  id: string
  tenantId?: string
  caseId?: string
  question: string
  approvedAnswer: string
  practiceHint?: string
  sourceResearchId?: string
  createdAt: string
}
